export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILED = 'LOAD_FAILED';

export const GETADMIN_SUCCESS = 'GETADMIN_SUCCESS';
export const GETADMIN_FAILURE = 'GETADMIN_FAILURE';
export const LASTLOGIN_SUCCESS = 'LASTLOGIN_SUCCESS';
export const LASTLOGIN_FAILURE = 'LASTLOGIN_FAILURE';
export const CLEAR_ADMINS = 'CLEAR_ADMINS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GETREQUEST_SUCCESS = 'GETREQUEST_SUCCESS';
export const GETREQUEST_FAILURE = 'GETREQUEST_FAILURE';
export const CLEAR_REQUESTS = 'CLEAR_REQUESTS';

export const GETSTUDENTS_SUCCESS = 'GETSTUDENTS_SUCCESS';
export const GETSTUDENTS_FAILURE = 'GETSTUDENTS_FAILURE';
export const CLEAR_STUDENTS = 'CLEAR_STUDENTS';

export const GETLOCATIONS_SUCCESS = 'GETLOCATIONS_SUCCESS';
export const GETLOCATIONS_FAILURE = 'GETLOCATIONS_FAILURE';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
