export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILED = 'LOAD_FAILED';

export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAILURE = 'GETUSER_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GETREQUEST_SUCCESS = 'GETREQUEST_SUCCESS';
export const GETREQUEST_FAILURE = 'GETREQUEST_FAILURE';
export const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
